import cgi

data = cgi.FieldStorage()
name = data.getvalue("name")
price = data.getvalue("price")
available = data.getvalue("available")
description = data.getvalue("description")

print("Content-Type: text/html")
print()
print("<!DOCTYPE HTML>")
print("<html>")
print("<head>")
print("<title>Student details</title>")
print("</head>")
print("<body>")
print("<h1>Product added to stock</h1>")
print("<p>Name: {}</p>".format(name))
print("<p>Price: {}</p>".format(price))
print("<p>Available: {}</p>".format(available))
print("<p>Description: {}</p>".format(description))
print("<a href=\"AdminFunctionalities.html\">Back</a>")
print("</body>")
print("</html>")